ENV_STACK_NAME = "SWARM_STACK_NAME"

ENV_SERVICE_ID = "SWARM_SERVICE_ID"
ENV_SERVICE_NAME = "SWARM_SERVICE_NAME"

ENV_TASK_ID = "SWARM_TASK_ID"
ENV_TASK_NAME = "SWARM_TASK_NAME"
ENV_TASK_SLOT = "SWARM_TASK_SLOT"

ENV_NODE_ID = "SWARM_NODE_ID"
ENV_NODE_NAME = "SWARM_NODE_NAME"
